module Rss (rss) where

import           Data.Text ( Text )
import qualified Data.Text as T
import           Data.Time ( UTCTime (..), defaultTimeLocale, formatTime,
                             fromGregorian, getCurrentTime )

import           Typ

rss :: Text -> [(Doc, [Text], Text)] -> IO Text
rss url entries = do
   now <- getCurrentTime
   let bld = formatRFC2822 now
   pure $ T.concat
      [ "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
      , "<rss version=\"2.0\">\n"
      , "   <channel>\n"
      , "      <title>Lμthenwałd's Blog</title>\n"
      , "      <link>", url, "</link>\n"
      , "      <description>personal blog generated by lacuna</description>\n"
      , "      <generator>lacuna</generator>\n"
      , "      <language>en</language>\n"
      , "      <lastBuildDate>", bld, "</lastBuildDate>\n"
      , T.concat (map (item url) entries)
      , "   </channel>\n"
      , "</rss>\n"
      ]

item :: Text -> (Doc, [Text], Text) -> Text
item url (doc, _, pid) = T.concat
   [ "      <item>\n"
   , "         <title>", escXml (metTtl m), "</title>\n"
   , "         <link>", url, "/blogs/", pid, ".html</link>\n"
   , "         <pubDate>", pubRFC (metPub m), "</pubDate>\n"
   , "         <guid>", url, "/blogs/", pid, ".html</guid>\n"
   , "         <description><![CDATA[", metDsc m, "]]></description>\n"
   , "      </item>\n"
   ]
 where m = docMet doc

pubRFC :: Text -> Text
pubRFC pub =
   let (y, md)  = T.splitAt 4 pub
       (_, md') = T.splitAt 1 md
       (mo, d') = T.splitAt 2 md'
       (_, dy)  = T.splitAt 1 d'
       yr  = read (T.unpack y)  :: Integer
       mon = read (T.unpack mo) :: Int
       day = read (T.unpack dy) :: Int
       utc = UTCTime (fromGregorian yr mon day) 0
   in  formatRFC2822 utc

formatRFC2822 :: UTCTime -> Text
formatRFC2822 = T.pack . formatTime defaultTimeLocale "%a, %d %b %Y %H:%M:%S +0000"

escXml :: Text -> Text
escXml = T.concatMap go
 where
   go '&'  = "&amp;"
   go '<'  = "&lt;"
   go '>'  = "&gt;"
   go '"'  = "&quot;"
   go '\'' = "&#39;"
   go c    = T.singleton c
