-- title       = About
-- pubDate     = 2036-11-18
-- tags        = about, personal
-- description = Personal info, contact & projects.

-- | Lμthenwałd/Luth/λμτη, He/Him
--
-- @img me.webp
--
-- Working at the intersection/propagation of Programming Language Theory, Category Theory, & High-Performance Computing.
--
-- | Contact
--
-- Reachable by [email](mailto:luthenwald@pm.me). Would be my pleasure to hear from you.
--
-- ````````````````````````````````````````````````````````````````
-- -----BEGIN PGP PUBLIC KEY BLOCK-----
--
-- mDMEaaWe2RYJKwYBBAHaRw8BAQdA6WwBCw3rXlRckwbtBaiTZqKf5uVcUglsh6+4
-- /XT0RT+0L2x1dGhlbndhbGQgKGdlbmVyYWwgcHVycG9zZSkgPGx1dGhlbndhbGRA
-- cG0ubWU+iJMEExYKADsWIQRsi/Wc6vpgBqWdf7EsGv56B/cAgQUCaaWe2QIbAwUL
-- CQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRAsGv56B/cAgToXAQDXsg+Pi6wD
-- fYN5cLrbjyRbY7KdVuyNenkt8xADEk7PAgEAwp4ETpZUq665IGXEURapaStVdQ9N
-- TK861YsNLbZu6QS4OARppZ7ZEgorBgEEAZdVAQUBAQdA3eM2NjSbsmZDdp6ua79p
-- BBMvOGtEC47usZuVj2GfOHkDAQgHiHgEGBYKACAWIQRsi/Wc6vpgBqWdf7EsGv56
-- B/cAgQUCaaWe2QIbDAAKCRAsGv56B/cAgQz9AP4kHSktIsowrc4OBFU+zMrqMu69
-- 8qXHgX86KuirrCw+DAD/Zc9JN6Nb03QzGACq8phFhWMPJVKvtsCXeyxsq5hYUQk=
-- =DTwu
-- -----END PGP PUBLIC KEY BLOCK-----
-- ``````````````````````````````````````````````````````````````````
--
-- | Projects
--
-- || Splined
--
-- Iterative image reconstruction using random [cubic bézier](https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Cubic_B%C3%A9zier_curves)
-- strokes, accelerated on [metal](https://en.wikipedia.org/wiki/Metal_(API)).
--
-- [src](https://tangled.org/luthenwald.tngl.sh/splined) | [bad apple](https://youtu.be/oVTDzle9qz8?si=DIWqILNn21JHVsnL)
--
-- > The image used here is under open access by [The Met](https://www.metmuseum.org/hubs/open-access).
--
-- @img splined-i.webp
-- @img splined-o.webp
--
-- | Links
--
-- || Blogsites
--
-- - [Alexis King](https://lexi-lambda.github.io)
-- - [Bartosz Milewski](https://bartoszmilewski.com/)
-- - [Iago Leal de Freitas](https://iagoleal.com/)
-- - [Jesper Cockx](https://jesper.cx/)
-- - [Oleg Kiselyov](https://okmij.org/ftp/)
-- - [Tony Zorman](https://tony-zorman.com)
-- - [Wen Kokke](https://wen.works/)
--
-- || Textbooks
--
-- - [Beautiful Racket](https://beautifulracket.com/)
-- - [Category Theory for Programmers](https://github.com/hmemcpy/milewski-ctfp-pdf)
-- - [Programming Language Foundations in Agda](https://plfa.github.io/20.07/)
--
-- || Dissertations
--
-- - [Fexprs as the basis of Lisp function application; or, $vau: the ultimate abstraction](http://lambda-the-ultimate.org/node/4093)
--
-- || Entertainment
--
-- - [nLab](https://ncatlab.org/nlab/show/HomePage)
-- - [Stanford Encyclopedia of Philosophy](https://plato.stanford.edu/cgi-bin/encyclopedia/random)
