const std   = @import("std");
const types = @import("types.zig");

const Allocator = std.mem.Allocator;

pub fn generateFeed(
    alloc:    Allocator,
    blogs:    []types.Blog,
    base_url: []const u8, ) ![]const u8 {

    var xml: std.ArrayList(u8) = .{}; defer xml.deinit(alloc);

    try xml.appendSlice(alloc, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    try xml.appendSlice(alloc, "<rss version=\"2.0\">\n");
    try xml.appendSlice(alloc, "   <channel>\n");
    try xml.appendSlice(alloc, "      <title>Lμthenwałd's Blog</title>\n");
    try std.fmt.format(xml.writer(alloc), "      <link>{s}</link>\n", .{base_url});
    try xml.appendSlice(alloc, "      <description>personal blog generated by lacuna</description>\n");
    try xml.appendSlice(alloc, "      <generator>lacuna</generator>\n");
    try xml.appendSlice(alloc, "      <language>en</language>\n");

    const now = std.time.timestamp();
    const rfc2822_date = try formatRFC2822(alloc, now); defer alloc.free(rfc2822_date);
    try std.fmt.format(xml.writer(alloc), "      <lastBuildDate>{s}</lastBuildDate>\n", .{rfc2822_date});

    for (blogs) |blog| {
        try xml.appendSlice(alloc, "      <item>\n");
        try std.fmt.format(xml.writer(alloc), "         <title>{s}</title>\n", .{escapeXml(blog.title)});
        try std.fmt.format(xml.writer(alloc), "         <link>{s}/blogs/{s}.html</link>\n", .{ base_url, blog.pageid });

        const pub_timestamp = try parseDate(blog.pub_date);
        const pub_rfc2822 = try formatRFC2822(alloc, pub_timestamp);
        defer alloc.free(pub_rfc2822);
        try std.fmt.format(xml.writer(alloc), "         <pubDate>{s}</pubDate>\n", .{pub_rfc2822});

        try std.fmt.format(xml.writer(alloc), "         <guid>{s}/blogs/{s}.html</guid>\n", .{ base_url, blog.pageid });
        try std.fmt.format(xml.writer(alloc), "         <description><![CDATA[{s}]]></description>\n", .{blog.description});
        try xml.appendSlice(alloc, "      </item>\n");
    }

    try xml.appendSlice(alloc, "   </channel>\n");
    try xml.appendSlice(alloc, "</rss>\n");

    return xml.toOwnedSlice(alloc); }

fn parseDate(date_str: []const u8) !i64 {
   if (date_str.len != 10) return error.InvalidDateFormat;

   const year = try std.fmt.parseInt(i32, date_str[0..4], 10);
   const month = try std.fmt.parseInt(u8, date_str[5..7], 10);
   const day = try std.fmt.parseInt(u8, date_str[8..10], 10);

   const days_in_month = [_]u8{ 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };

   const is_leap = (@mod(year, 4) == 0 and @mod(year, 100) != 0) or (@mod(year, 400) == 0);
   var day_of_year: i32 = day;

   for (0..month - 1) |m| { day_of_year += days_in_month[m]; if (m == 1 and is_leap) { day_of_year += 1; } }

   const days_in_400_years: i64 = 146097;
   const days_in_100_years: i64 = 36524;
   const days_in_4_years: i64 = 1461;
   const days_in_year: i64 = 365;

   const y = year - 1970;
   const leap_cycles = @divFloor(y, 400);
   var days: i64 = leap_cycles * days_in_400_years;
   var y_rem = @mod(y, 400);

   const century_cycles = @divFloor(y_rem, 100);
   days += century_cycles * days_in_100_years;
   y_rem = @mod(y_rem, 100);

   const quad_cycles = @divFloor(y_rem, 4);
   days += quad_cycles * days_in_4_years;
   y_rem = @mod(y_rem, 4);

   days += y_rem * days_in_year;
   days += day_of_year;

   return days * 86400; }

fn formatRFC2822(alloc: Allocator, timestamp: i64) ![]const u8 {
   const epoch_seconds: u64 = @intCast(timestamp);
   const epoch = std.time.epoch.EpochSeconds{ .secs = epoch_seconds };
   const day_seconds = epoch.getDaySeconds();
   const epoch_day = epoch.getEpochDay();
   const year_day = epoch_day.calculateYearDay();
   const month_day = year_day.calculateMonthDay();

   const weekday_names = [_][]const u8{ "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" };
   const month_names = [_][]const u8{ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };

   const weekday = @mod(@as(i64, @intCast(epoch_day.day)) + 4, 7);

   return try std.fmt.allocPrint(
      alloc,
      "{s}, {d:0>2} {s} {d} {d:0>2}:{d:0>2}:{d:0>2} +0000",
      .{ weekday_names[@intCast(weekday)],
         month_day.day_index + 1,
         month_names[month_day.month.numeric() - 1],
         year_day.year,
         day_seconds.getHoursIntoDay(),
         day_seconds.getMinutesIntoHour(),
         day_seconds.getSecondsIntoMinute(), }, ); }

fn escapeXml(text: []const u8) []const u8 { return text; }
